from pathlib import Path
p=Path('Source/LarGridPivot.Grid.pas')
s=p.read_text(encoding='utf-8')
old='''procedure TLarGridPivot.SetShowRowTotals(const Value:Boolean);\nbegin\n if Value=FShowRowTotals then Exit;\n FShowRowTotals:=Value;\n RefreshViewOnly;\n UpdateScrollBars;\n Update;\nend;'''
new='''procedure TLarGridPivot.SetShowRowTotals(const Value:Boolean);\nbegin\n if Value=FShowRowTotals then Exit;\n FShowRowTotals:=Value;\n { Rebuild geometry first, then clamp horizontal position to the new content width. }\n FViewDirty:=True;\n FScrollDirty:=True;\n BuildViewInfo;\n UpdateScrollBars;\n FHScrollPos:=GetScrollPos(Handle,SB_HORZ);\n FViewDirty:=True;\n BuildViewInfo;\n Invalidate;\n Update;\nend;'''
assert old in s
s=s.replace(old,new,1)
old2='''procedure TLarGridPivot.SelectCellsInRect(const ARect:TRect;AAdd:Boolean);\nvar VI:TLarPivotViewItem; R,PaintR:TRect;\nbegin\n FSelectedCells.Clear;\n if AAdd then FSelectedCells.Assign(FSelectionBase);\n for VI in FViewInfo.Items do\n  if VI.Kind in [pvekRowValue,pvekDataCell,pvekTotalCell,pvekGrandTotalCell] then begin\n   R:=VI.Bounds;\n   { Row hierarchy is frozen horizontally; compare it in screen-X coordinates. }\n   if VI.Kind=pvekRowValue then OffsetRect(R,FHScrollPos,0);\n   if (R.Right>ARect.Left) and (R.Left<ARect.Right) and (R.Bottom>ARect.Top) and (R.Top<ARect.Bottom) then\n    FSelectedCells.Add(CellSelectionKey(VI));\n  end;\n if HandleAllocated then begin\n  PaintR:=Rect(0,EffectiveFieldAreaHeight+(FViewInfo.HeaderLevels*FHeaderHeight),ClientWidth,ClientHeight);\n  InvalidateRect(Handle,@PaintR,False);\n end else Invalidate;\nend;'''
new2='''procedure TLarGridPivot.SelectCellsInRect(const ARect:TRect;AAdd:Boolean);\nvar VI:TLarPivotViewItem; R,PaintR:TRect; OldSelection:TStringList; K:string; Changed:Boolean;\nbegin\n OldSelection:=TStringList.Create;\n try\n  OldSelection.Sorted:=True; OldSelection.Duplicates:=dupIgnore;\n  OldSelection.Assign(FSelectedCells);\n  FSelectedCells.Clear;\n  if AAdd then FSelectedCells.Assign(FSelectionBase);\n  for VI in FViewInfo.Items do\n   if VI.Kind in [pvekRowValue,pvekDataCell,pvekTotalCell,pvekGrandTotalCell] then begin\n    R:=VI.Bounds;\n    if VI.Kind=pvekRowValue then OffsetRect(R,FHScrollPos,0);\n    if (R.Right>ARect.Left) and (R.Left<ARect.Right) and (R.Bottom>ARect.Top) and (R.Top<ARect.Bottom) then\n     FSelectedCells.Add(CellSelectionKey(VI));\n   end;\n  { Repaint only cells whose selected state actually changed. }\n  if HandleAllocated then begin\n   for VI in FViewInfo.Items do\n    if VI.Kind in [pvekRowValue,pvekDataCell,pvekTotalCell,pvekGrandTotalCell] then begin\n     K:=CellSelectionKey(VI);\n     Changed:=(OldSelection.IndexOf(K)>=0)<>(FSelectedCells.IndexOf(K)>=0);\n     if Changed then begin\n      PaintR:=VI.Bounds;\n      OffsetRect(PaintR,-FHScrollPos,-FVScrollPos);\n      if VI.Kind=pvekRowValue then OffsetRect(PaintR,FHScrollPos,0);\n      InvalidateRect(Handle,@PaintR,False);\n     end;\n    end;\n  end else Invalidate;\n finally\n  OldSelection.Free;\n end;\nend;'''
assert old2 in s
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')
